import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Code2, PencilRuler, ShieldCheck, Users } from 'lucide-react';
import Card from './ui/Card';

function WorkspacePreview() {
  return <Card className="relative overflow-hidden p-5 sm:p-7"><div className="absolute -right-12 -top-12 h-52 w-52 rounded-full bg-blue-200/60 blur-3xl" /><div className="absolute -bottom-10 -left-10 h-44 w-44 rounded-full bg-violet-200/60 blur-3xl" />
    <div className="relative grid gap-4 sm:grid-cols-5"><div className="rounded-xl border border-sync-border bg-slate-50 p-4 sm:col-span-3"><div className="mb-4 flex items-center gap-2 border-b border-sync-border pb-3 text-sm font-semibold"><PencilRuler className="h-4 w-4 text-sync-accent" />Architecture whiteboard</div><svg viewBox="0 0 360 150" className="h-40 w-full"><path d="M55 36H180M180 36H304M55 36L112 110M180 36L112 110M180 36L246 110M304 36L246 110" stroke="#7C3AED" strokeWidth="2" /><circle cx="55" cy="36" r="16" fill="white" stroke="#E2E8F0" /><circle cx="180" cy="36" r="16" fill="white" stroke="#E2E8F0" /><circle cx="304" cy="36" r="16" fill="white" stroke="#E2E8F0" /><circle cx="112" cy="110" r="16" fill="#7C3AED" /><circle cx="246" cy="110" r="16" fill="#2563EB" /></svg><motion.div animate={{ x: [5, 110, 75], y: [0, 42, 18] }} transition={{ duration: 7, repeat: Infinity }} className="flex w-fit items-center gap-1 rounded bg-sync-text px-2 py-1 text-[10px] text-white"><span className="h-2 w-2 rounded-full bg-sync-success" />Alex</motion.div></div>
      <div className="rounded-xl bg-slate-950 p-4 font-mono text-xs leading-6 text-slate-300 sm:col-span-2"><div className="mb-3 flex items-center gap-2 border-b border-slate-800 pb-3 font-sans text-sm"><Code2 className="h-4 w-4 text-sync-success" />server.ts</div><span className="text-emerald-400">import</span> {'{ '}Server{' }'}<br /><span className="text-sky-400">const</span> room = new Server({'{'}<br />&nbsp;sync: <span className="text-amber-300">true</span>,<br />&nbsp;latency: <span className="text-amber-300">25</span><br />{'}'});</div></div></Card>;
}

export default function Hero() { return <section className="grid items-center gap-12 pb-24 pt-36 md:grid-cols-2 lg:gap-16"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-bold uppercase tracking-wide text-sync-primary"><ShieldCheck className="h-4 w-4" />Powered by real-time sync</div><h1 className="max-w-2xl text-5xl font-extrabold leading-[1.05] tracking-tight sm:text-6xl lg:text-7xl">Collaborate in real time. <span className="text-sync-primary">Code.</span> <span className="text-sync-accent">Draw.</span> Build together.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-sync-text-secondary">SyncSpace gives teams one focused place to write notes, sketch ideas, and keep work moving together.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/login" className="inline-flex items-center gap-2 rounded-full bg-sync-primary px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700">Start collaborating <ArrowRight className="h-4 w-4" /></Link><a href="#features" className="inline-flex items-center gap-2 rounded-full border border-sync-border bg-white px-5 py-3 text-sm font-semibold hover:bg-slate-50"><Users className="h-4 w-4" />Explore features</a></div></div><WorkspacePreview /></section>; }
